CREATE TABLE IF NOT EXISTS fd_diagnosis_case (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id VARCHAR(20) NOT NULL DEFAULT '000000',
    case_code VARCHAR(64) NOT NULL,
    session_id BIGINT NULL,
    agent_id BIGINT NULL,
    user_id BIGINT NULL,
    asset_code VARCHAR(64) NOT NULL,
    question TEXT NOT NULL,
    query_start_time DATETIME NOT NULL,
    query_end_time DATETIME NOT NULL,
    status VARCHAR(32) NOT NULL,
    conclusion_json LONGTEXT NULL,
    root_hash CHAR(64) NULL,
    evidence_count INT NOT NULL DEFAULT 0,
    error_message VARCHAR(2000) NULL,
    create_dept BIGINT NULL,
    create_by BIGINT NULL,
    create_time DATETIME NULL,
    update_by BIGINT NULL,
    update_time DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_fd_case_tenant_code (tenant_id, case_code),
    KEY idx_fd_case_tenant_session (tenant_id, session_id),
    KEY idx_fd_case_tenant_asset_time (tenant_id, asset_code, query_start_time, query_end_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='故障诊断案例';

CREATE TABLE IF NOT EXISTS fd_diagnosis_step (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id VARCHAR(20) NOT NULL DEFAULT '000000',
    case_id BIGINT NOT NULL,
    step_no INT NOT NULL,
    step_type VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    input_json LONGTEXT NULL,
    output_summary_json LONGTEXT NULL,
    error_message VARCHAR(2000) NULL,
    started_at DATETIME NOT NULL,
    finished_at DATETIME NULL,
    create_dept BIGINT NULL,
    create_by BIGINT NULL,
    create_time DATETIME NULL,
    update_by BIGINT NULL,
    update_time DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_fd_step_tenant_case_no (tenant_id, case_id, step_no),
    KEY idx_fd_step_tenant_case_status (tenant_id, case_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='故障诊断步骤';

CREATE TABLE IF NOT EXISTS fd_evidence (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id VARCHAR(20) NOT NULL DEFAULT '000000',
    case_id BIGINT NOT NULL,
    step_id BIGINT NOT NULL,
    evidence_seq INT NOT NULL,
    evidence_code VARCHAR(32) NOT NULL,
    evidence_type VARCHAR(64) NOT NULL,
    source_system VARCHAR(64) NOT NULL,
    source_reference VARCHAR(512) NULL,
    request_json LONGTEXT NULL,
    result_summary_json LONGTEXT NOT NULL,
    source_record_count INT NULL,
    source_digest CHAR(64) NULL,
    request_hash CHAR(64) NOT NULL,
    result_hash CHAR(64) NOT NULL,
    previous_hash CHAR(64) NULL,
    current_hash CHAR(64) NOT NULL,
    hash_version VARCHAR(16) NOT NULL DEFAULT 'SHA256_V1',
    quality_score DECIMAL(8,4) NULL,
    collected_at DATETIME NOT NULL,
    create_dept BIGINT NULL,
    create_by BIGINT NULL,
    create_time DATETIME NULL,
    update_by BIGINT NULL,
    update_time DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_fd_evidence_tenant_case_seq (tenant_id, case_id, evidence_seq),
    UNIQUE KEY uk_fd_evidence_tenant_case_code (tenant_id, case_id, evidence_code),
    KEY idx_fd_evidence_tenant_case_type (tenant_id, case_id, evidence_type),
    KEY idx_fd_evidence_tenant_step (tenant_id, step_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='故障诊断证据';

CREATE TABLE IF NOT EXISTS fd_conclusion_evidence_rel (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id VARCHAR(20) NOT NULL DEFAULT '000000',
    case_id BIGINT NOT NULL,
    conclusion_code VARCHAR(64) NOT NULL,
    evidence_id BIGINT NOT NULL,
    relation_type VARCHAR(32) NOT NULL,
    weight DECIMAL(8,4) NULL,
    create_dept BIGINT NULL,
    create_by BIGINT NULL,
    create_time DATETIME NULL,
    update_by BIGINT NULL,
    update_time DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_fd_conclusion_evidence_rel (tenant_id, case_id, conclusion_code, evidence_id, relation_type),
    KEY idx_fd_conclusion_evidence_case_code (tenant_id, case_id, conclusion_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='诊断结论证据关联';
